import { IInitialState } from './types/initialStateTypes';

export const initialState: IInitialState = {
  categories: [
    'nature',
    'space',
    'love',
    'tree',
    'ocean',
    'people',
    'city',
    'architecture',
    'forest',
    'car',
    'music',
    'robot',
    'movies',
    'cartoons',
    'food',
    'coffee',
    'sculptures',
    'japan',
    'clothes',
    'america',
    'beautiful places',
    'planet',
    'happiness',
    'new Year',
    'the actors',
    'books',
    'animals',
    'cats',
    'friendship',
    'flowers',
    'technologies',
    'islands',
    'maldives',
    'night city',
    'sport',
    'races',
    'sports cars',
    'cosplay',
    'history',
    'chess',
  ],
  photo: {
    photos: [],
    loading: false,
    error: null,
    total_results: 0,
  },
};
